__title__ = 'pims'
__description__ = 'Cytomine Python Image Server'
__url__ = 'https://doc.uliege.cytomine.org'
__version__ = '0.1.0'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Cytomine.org'
